// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2l5nyjNBaXTlLxC3M4Q-X_Rm4Q1lpO8Q',
    appId: '1:172600208833:web:24dba92019de45913f1340',
    messagingSenderId: '172600208833',
    projectId: 'attendanceapp-c9433',
    authDomain: 'attendanceapp-c9433.firebaseapp.com',
    storageBucket: 'attendanceapp-c9433.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZbpbKD3PTPiavXiavvzeX_9Hybw8waOk',
    appId: '1:172600208833:ios:075c8b60528d7a8c3f1340',
    messagingSenderId: '172600208833',
    projectId: 'attendanceapp-c9433',
    storageBucket: 'attendanceapp-c9433.appspot.com',
    iosClientId: '172600208833-pt8q99528a8rfgv3hovqvjtede5m6jj1.apps.googleusercontent.com',
    iosBundleId: 'com.kodekrew.attendanceApp',
  );
}
